server {
    listen 80;
    server_name posters.tribault.com;

    root /home/thomas/ppa/client/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;  # required for Vue Router (createWebHistory)
    }
}
